// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCOzHtXjPeM35oI720u20bdCl4ssa_8Cc',
    appId: '1:153092000952:web:40fffeb6dfaacb13e8384d',
    messagingSenderId: '153092000952',
    projectId: 'visitante-13026',
    authDomain: 'visitante-13026.firebaseapp.com',
    storageBucket: 'visitante-13026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHnrz1NOeHbJCeXF4o5mrvXg2Rk6jk3KU',
    appId: '1:153092000952:android:73de25c02ec2f98ce8384d',
    messagingSenderId: '153092000952',
    projectId: 'visitante-13026',
    storageBucket: 'visitante-13026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD162py6EFlIvkzNvKSQHJkOuI5bFS-2zc',
    appId: '1:153092000952:ios:647d46dd241ddf52e8384d',
    messagingSenderId: '153092000952',
    projectId: 'visitante-13026',
    storageBucket: 'visitante-13026.firebasestorage.app',
    iosBundleId: 'com.example.visitante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD162py6EFlIvkzNvKSQHJkOuI5bFS-2zc',
    appId: '1:153092000952:ios:647d46dd241ddf52e8384d',
    messagingSenderId: '153092000952',
    projectId: 'visitante-13026',
    storageBucket: 'visitante-13026.firebasestorage.app',
    iosBundleId: 'com.example.visitante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCOzHtXjPeM35oI720u20bdCl4ssa_8Cc',
    appId: '1:153092000952:web:cd42eb23e7f9e3c0e8384d',
    messagingSenderId: '153092000952',
    projectId: 'visitante-13026',
    authDomain: 'visitante-13026.firebaseapp.com',
    storageBucket: 'visitante-13026.firebasestorage.app',
  );
}
